import BootstrapClient from "@/component/BootstrapClient";
import "./globals.css";
import "../../public/assets/css/style.css"
import "bootstrap/dist/css/bootstrap.min.css";

import LayoutClient from "@/component/LayoutClient";

export const metadata = {
  title: "Sanskargroup.in",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <head>
        <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
      </head>
      <body style={{ backgroundImage: "url('/assets/images/bg.jpg') !important" }}>
        <BootstrapClient />
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
